### ISSUE TITLE
crashed on Macbook Prp M1

### ISSUE THREAD

**Issue by andrewtsuei** [eddiesigner/sketch-map-generator#65] opened 2021-01-20 12:00 UTC
Crashed on Sketch 70.3 with Macbook Pro M1

**Comment by eddiesigner** [comment] 2021-01-27 19:41
Hmm I can't reproduce it since I don't have a M1 Macbook Pro. This plugin is built with [skpm](https://github.com/skpm) and uses [sketch-module-web-view](https://github.com/skpm/sketch-module-web-view) for the UI, that module [has apparently issues on M1 Macbooks](https://github.com/skpm/sketch-module-web-view/issues/168). You can expect this kind of issues since the M1 architecture is different, hopefully those kind of issues will be less common over time, at the moment I can't really do something about it.

As an alternative you can run Sketch with "Open using Rosetta", that should work for now.

**Comment by eddiesigner** [comment] 2021-02-20 12:41
According to [this comment](https://github.com/skpm/sketch-module-web-view/issues/168#issuecomment-782006309), this should be fixed in Sketch 70.5.

**Closed as completed by eddiesigner** 2021-02-20 12:41 UTC
