### ISSUE TITLE
Is it possible to produce maps bigger in size?

### ISSUE THREAD

**Issue by giap** [eddiesigner/sketch-map-generator#54] opened 2020-04-03 09:34 UTC
I am designing a map-centric interface and your plugin has served me greatly in this. One thing I am missing, though, is that it has a strong limitation on the size of the tile it can produce. I design on a canvas of 1440x900, would it be possible to produce a continuous image that has that size?

Right now I am working around the limitation producing different tiles and overlapping them, but it's a bit of a petty workflow and I am wondering if it can actually be automised.

Thanks!

**Comment by eddiesigner** [comment] 2020-04-06 09:59
I understand your concern, the problem is that Google Maps has the following restriction:

> Static Maps images can be returned in any size up to 640 x 640 pixels.
Source: https://developers.google.com/maps/documentation/maps-static/usage-and-billing

Although it seems like you can request access to 2048x2048 as described here: https://issuetracker.google.com/issues/110570733#comment6

I'm not sure if it's something that is currently working but you can try ;)

**Comment by eddiesigner** [comment] 2020-04-16 07:18
I will close this for now, please feel free to reopen it if needed.

**Closed as completed by eddiesigner** 2020-04-16 07:18 UTC
